### ISSUE TITLE
any cMake or VS solution for building your SW?

### ISSUE THREAD

**Issue by Thanh-Binh** [x75/rlcpp#1]
Do you have any any cMake or VS solution for building your SW? Thanks

**Comment by x75** [comment]
hey, haven't looked at that project in a while, was the usual quick hack to #makeitworkforme. cmake should be possible, if i find some time i'll try and look into it. VS is not my domain so somebody else would need to jump in and make a pull request. bst

**Comment by Thanh-Binh** [comment]
Thank for your help. Do you have any application with rl?

**Comment by x75** [comment]
@Thanh-Binh just added a cmake file that should enable you to build the ROS versions of the executables.

**Comment by x75** [comment]
@Thanh-Binh sorry once more regarding 'application': obviously this is not complete as i using some python code implementing the actual systems at the ROS receiver side that would compute one time step and send back the results to rlcpp. This was all just a quick test, maybe i manage to put it together.

**Comment by Thanh-Binh** [comment]
thanks
